import initDevice from "/src/js/device";
import initAria from "/src/js/aria";
import initAnchor from "/src/js/anchor";
import initModals from "/src/js/modals.js";
import initHeaderNav from "/src/js/header-nav";
import initSearch from "/src/js/search";
import initMegamenu from "/src/js/megamenu";
import initFilter from "/src/js/filter";
import initHeroSlider from "/src/js/swiper-hero";
import initPromoSlider from "/src/js/swiper-promo";
import initLoyaltySlider from "/src/js/swiper-loyalty";
import initCardProducts from "/src/js/card-product";
import initProduct from "/src/js/product/product.js";

initDevice();
initAria();
initAnchor();
initModals();
initHeaderNav();
initSearch();
initMegamenu();
initFilter();
initHeroSlider();
initPromoSlider();
initLoyaltySlider();
initCardProducts();
initProduct();
